pipeline:
  build:
    image: debian
    commands:
      - apt-get -qq update
      - apt-get -qq install lrzsz git python python-pip python3
      - pip install -r requirements-testing.txt
      - tox
